package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeDeviceAddress;
import org.bubblecloud.zigbee.v3.ZigBeeNetworkManager;
import org.bubblecloud.zigbee.v3.zcl.ZclAttribute;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ConfigureReportingCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ConfigureReportingResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.DefaultResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.DiscoverAttributesCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.DiscoverAttributesResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ReadAttributesCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ReadAttributesResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ReadAttributesStructuredCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ReadReportingConfigurationCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ReadReportingConfigurationResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.ReportAttributesCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.WriteAttributesCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.WriteAttributesNoResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.WriteAttributesResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.WriteAttributesStructuredCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.WriteAttributesStructuredResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.general.WriteAttributesUndividedCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclDataType;

/**
 * <b>General</b> cluster implementation (<i>Cluster ID 0xFFFF</i>).
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclGeneralCluster extends ZclCluster {
    // Cluster ID
    public static final int CLUSTER_ID = 0xFFFF;

    // Cluster Name
    public static final String CLUSTER_NAME = "General";

    // Attribute initialisation
    protected Map<Integer, ZclAttribute> initializeAttributes() {
        Map<Integer, ZclAttribute> attributeMap = new HashMap<Integer, ZclAttribute>(0);


        return attributeMap;
    }

    /**
     * Default constructor.
     */
    public ZclGeneralCluster(final ZigBeeNetworkManager zigbeeManager, final ZigBeeDeviceAddress zigbeeAddress) {
        super(zigbeeManager, zigbeeAddress, CLUSTER_ID, CLUSTER_NAME);
    }



    /**
     * The Read Attributes Command
     * <p>
     * The read attributes command is generated when a device wishes to determine the
     * values of one or more attributes located on another device. Each attribute
     * identifier field shall contain the identifier of the attribute to be read.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> readAttributesCommand() {
        return send(new ReadAttributesCommand());
    }


    /**
     * The  Read Attributes Response
     * <p>
     * The read attributes response command is generated in response to a read attributes
     * or read attributes structured command. The command frame shall contain a read
     * attribute status record for each attribute identifier specified in the original read
     * attributes or read attributes structured command. For each read attribute status
     * record, the attribute identifier field shall contain the identifier specified in the
     * original read attributes or read attributes structured command.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> readAttributesResponse() {
        return send(new ReadAttributesResponse());
    }


    /**
     * The Write Attributes Command
     * <p>
     * The write attributes command is generated when a device wishes to change the
     * values of one or more attributes located on another device. Each write attribute
     * record shall contain the identifier and the actual value of the attribute to be
     * written.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> writeAttributesCommand() {
        return send(new WriteAttributesCommand());
    }


    /**
     * The Write Attributes Undivided Command
     * <p>
     * The write attributes undivided command is generated when a device wishes to
     * change the values of one or more attributes located on another device, in such a
     * way that if any attribute cannot be written (e.g. if an attribute is not implemented
     * on the device, or a value to be written is outside its valid range), no attribute
     * values are changed.
     * <br>
     * In all other respects, including generation of a write attributes response command,
     * the format and operation of the command is the same as that of the write attributes
     * command, except that the command identifier field shall be set to indicate the
     * write attributes undivided command.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> writeAttributesUndividedCommand() {
        return send(new WriteAttributesUndividedCommand());
    }


    /**
     * The  Write Attributes Response
     * <p>
     * The write attributes response command is generated in response to a write
     * attributes command.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> writeAttributesResponse() {
        return send(new WriteAttributesResponse());
    }


    /**
     * The  Write Attributes No Response
     * <p>
     * The write attributes no response command is generated when a device wishes to
     * change the value of one or more attributes located on another device but does not
     * require a response. Each write attribute record shall contain the identifier and the
     * actual value of the attribute to be written.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> writeAttributesNoResponse() {
        return send(new WriteAttributesNoResponse());
    }


    /**
     * The Configure Reporting Command
     * <p>
     * The Configure Reporting command is used to configure the reporting mechanism
     * for one or more of the attributes of a cluster.
     * <br>
     * The individual cluster definitions specify which attributes shall be available to this
     * reporting mechanism, however specific implementations of a cluster may make
     * additional attributes available.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> configureReportingCommand() {
        return send(new ConfigureReportingCommand());
    }


    /**
     * The  Configure Reporting Response
     * <p>
     * The Configure Reporting Response command is generated in response to a
     * Configure Reporting command.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> configureReportingResponse() {
        return send(new ConfigureReportingResponse());
    }


    /**
     * The Read Reporting Configuration Command
     * <p>
     * The Read Reporting Configuration command is used to read the configuration
     * details of the reporting mechanism for one or more of the attributes of a cluster.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> readReportingConfigurationCommand() {
        return send(new ReadReportingConfigurationCommand());
    }


    /**
     * The  Read Reporting Configuration Response
     * <p>
     * The Read Reporting Configuration Response command is used to respond to a
     * Read Reporting Configuration command.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> readReportingConfigurationResponse() {
        return send(new ReadReportingConfigurationResponse());
    }


    /**
     * The Report Attributes Command
     * <p>
     * The report attributes command is used by a device to report the values of one or
     * more of its attributes to another device, bound a priori. Individual clusters, defined
     * elsewhere in the ZCL, define which attributes are to be reported and at what
     * interval.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> reportAttributesCommand() {
        return send(new ReportAttributesCommand());
    }


    /**
     * The  Default Response
     * <p>
     * The default response command is generated when a device receives a unicast
     * command, there is no other relevant response specified for the command, and
     * either an error results or the Disable default response bit of its Frame control field
     * is set to 0.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> defaultResponse() {
        return send(new DefaultResponse());
    }


    /**
     * The Discover Attributes Command
     * <p>
     * The discover attributes command is generated when a remote device wishes to
     * discover the identifiers and types of the attributes on a device which are supported
     * within the cluster to which this command is directed.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> discoverAttributesCommand() {
        return send(new DiscoverAttributesCommand());
    }


    /**
     * The  Discover Attributes Response
     * <p>
     * The discover attributes response command is generated in response to a discover
     * attributes command.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> discoverAttributesResponse() {
        return send(new DiscoverAttributesResponse());
    }


    /**
     * The Read Attributes Structured Command
     * <p>
     * The read attributes command is generated when a device wishes to determine the
     * values of one or more attributes, or elements of attributes, located on another
     * device. Each attribute identifier field shall contain the identifier of the attribute to
     * be read.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> readAttributesStructuredCommand() {
        return send(new ReadAttributesStructuredCommand());
    }


    /**
     * The Write Attributes Structured Command
     * <p>
     * The write attributes structured command is generated when a device wishes to
     * change the values of one or more attributes located on another device. Each write
     * attribute record shall contain the identifier and the actual value of the attribute, or
     * element thereof, to be written.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> writeAttributesStructuredCommand() {
        return send(new WriteAttributesStructuredCommand());
    }


    /**
     * The  Write Attributes Structured Response
     * <p>
     * The write attributes structured response command is generated in response to a
     * write attributes structured command.
     * </p>
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> writeAttributesStructuredResponse() {
        return send(new WriteAttributesStructuredResponse());
    }

}
