package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeDeviceAddress;
import org.bubblecloud.zigbee.v3.ZigBeeNetworkManager;
import org.bubblecloud.zigbee.v3.zcl.ZclAttribute;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.AddSceneCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.AddSceneResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.GetSceneMembershipCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.GetSceneMembershipResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.RecallSceneCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.RemoveAllScenesCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.RemoveAllScenesResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.RemoveSceneCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.RemoveSceneResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.StoreSceneCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.StoreSceneResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.ViewSceneCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.scenes.ViewSceneResponse;
import org.bubblecloud.zigbee.v3.zcl.field.*;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclDataType;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclFieldType;

/**
 * <b>Scenes</b> cluster implementation (<i>Cluster ID 0x0005</i>).
 * <p>
 * The scenes cluster provides attributes and commands for setting up and recalling
 * scenes. Each scene corresponds to a set of stored values of specified attributes for
 * one or more clusters on the same end point as the scenes cluster.
 * <br>
 * In most cases scenes are associated with a particular group ID. Scenes may also
 * exist without a group, in which case the value 0x0000 replaces the group ID. Note
 * that extra care is required in these cases to avoid a scene ID collision, and that
 * commands related to scenes without a group may only be unicast, i.e.: they may
 * not be multicast or broadcast.
 * </p>
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclScenesCluster extends ZclCluster {
    // Cluster ID
    public static final int CLUSTER_ID = 0x0005;

    // Cluster Name
    public static final String CLUSTER_NAME = "Scenes";

    // Attribute constants
    public static final int ATTR_SCENECOUNT = 0x0000;
    public static final int ATTR_CURRENTSCENE = 0x0001;
    public static final int ATTR_CURRENTGROUP = 0x0002;
    public static final int ATTR_SCENEVALID = 0x0003;
    public static final int ATTR_NAMESUPPORT = 0x0004;
    public static final int ATTR_LASTCONFIGUREDBY = 0x0005;

    // Attribute initialisation
    protected Map<Integer, ZclAttribute> initializeAttributes() {
        Map<Integer, ZclAttribute> attributeMap = new HashMap<Integer, ZclAttribute>(6);

        attributeMap.put(ATTR_SCENECOUNT, new ZclAttribute(0, "SceneCount", ZclDataType.UNSIGNED_8_BIT_INTEGER, true, true, false, false));
        attributeMap.put(ATTR_CURRENTSCENE, new ZclAttribute(1, "CurrentScene", ZclDataType.UNSIGNED_8_BIT_INTEGER, true, true, false, false));
        attributeMap.put(ATTR_CURRENTGROUP, new ZclAttribute(2, "CurrentGroup", ZclDataType.UNSIGNED_16_BIT_INTEGER, true, true, false, false));
        attributeMap.put(ATTR_SCENEVALID, new ZclAttribute(3, "SceneValid", ZclDataType.BOOLEAN, true, true, false, false));
        attributeMap.put(ATTR_NAMESUPPORT, new ZclAttribute(4, "NameSupport", ZclDataType.BITMAP_8_BIT, true, true, false, false));
        attributeMap.put(ATTR_LASTCONFIGUREDBY, new ZclAttribute(5, "LastConfiguredBy", ZclDataType.IEEE_ADDRESS, false, true, false, false));

        return attributeMap;
    }

    /**
     * Default constructor.
     */
    public ZclScenesCluster(final ZigBeeNetworkManager zigbeeManager, final ZigBeeDeviceAddress zigbeeAddress) {
        super(zigbeeManager, zigbeeAddress, CLUSTER_ID, CLUSTER_NAME);
    }



    /**
     * Get the <i>SceneCount</i> attribute
     * <p>
     * The SceneCount attribute specifies the number of scenes currently in the device's
     * scene table.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getSceneCountAsync() {
        return read(ATTR_SCENECOUNT);
    }


    /**
     * Synchronously get the <i>SceneCount</i> attribute
     * <p>
     * The SceneCount attribute specifies the number of scenes currently in the device's
     * scene table.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getSceneCount() {
        return (Integer) readSync(ATTR_SCENECOUNT);
    }


    /**
     * Get the <i>CurrentScene</i> attribute
     * <p>
     * <br>
     * The CurrentScene attribute holds the Scene ID of the scene last invoked.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getCurrentSceneAsync() {
        return read(ATTR_CURRENTSCENE);
    }


    /**
     * Synchronously get the <i>CurrentScene</i> attribute
     * <p>
     * <br>
     * The CurrentScene attribute holds the Scene ID of the scene last invoked.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getCurrentScene() {
        return (Integer) readSync(ATTR_CURRENTSCENE);
    }


    /**
     * Get the <i>CurrentGroup</i> attribute
     * <p>
     * <br>
     * The CurrentGroup attribute holds the Group ID of the scene last invoked, or
     * 0x0000 if the scene last invoked is not associated with a group.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getCurrentGroupAsync() {
        return read(ATTR_CURRENTGROUP);
    }


    /**
     * Synchronously get the <i>CurrentGroup</i> attribute
     * <p>
     * <br>
     * The CurrentGroup attribute holds the Group ID of the scene last invoked, or
     * 0x0000 if the scene last invoked is not associated with a group.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getCurrentGroup() {
        return (Integer) readSync(ATTR_CURRENTGROUP);
    }


    /**
     * Get the <i>SceneValid</i> attribute
     * <p>
     * <br>
     * The SceneValid attribute indicates whether the state of the device corresponds to
     * that associated with the CurrentScene and CurrentGroup attributes. TRUE
     * indicates that these attributes are valid, FALSE indicates that they are not valid.
     * <br>
     * Before a scene has been stored or recalled, this attribute is set to FALSE. After a
     * successful Store Scene or Recall Scene command it is set to TRUE. If, after a
     * scene is stored or recalled, the state of the device is modified, this attribute is set to
     * FALSE.
     * </p>
     * The attribute is of type {@link Boolean}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getSceneValidAsync() {
        return read(ATTR_SCENEVALID);
    }


    /**
     * Synchronously get the <i>SceneValid</i> attribute
     * <p>
     * <br>
     * The SceneValid attribute indicates whether the state of the device corresponds to
     * that associated with the CurrentScene and CurrentGroup attributes. TRUE
     * indicates that these attributes are valid, FALSE indicates that they are not valid.
     * <br>
     * Before a scene has been stored or recalled, this attribute is set to FALSE. After a
     * successful Store Scene or Recall Scene command it is set to TRUE. If, after a
     * scene is stored or recalled, the state of the device is modified, this attribute is set to
     * FALSE.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Boolean}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Boolean} attribute value, or null on error
     */
    public Boolean getSceneValid() {
        return (Boolean) readSync(ATTR_SCENEVALID);
    }


    /**
     * Get the <i>NameSupport</i> attribute
     * <p>
     * <br>
     * The most significant bit of the NameSupport attribute indicates whether or not
     * scene names are supported. A value of 1 indicates that they are supported, and a
     * value of 0 indicates that they are not supported.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getNameSupportAsync() {
        return read(ATTR_NAMESUPPORT);
    }


    /**
     * Synchronously get the <i>NameSupport</i> attribute
     * <p>
     * <br>
     * The most significant bit of the NameSupport attribute indicates whether or not
     * scene names are supported. A value of 1 indicates that they are supported, and a
     * value of 0 indicates that they are not supported.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getNameSupport() {
        return (Integer) readSync(ATTR_NAMESUPPORT);
    }


    /**
     * Get the <i>LastConfiguredBy</i> attribute
     * <p>
     * <br>
     * The LastConfiguredBy attribute is 64-bits in length and specifies the IEEE address
     * of the device that last configured the scene table.
     * <br>
     * The value 0xffffffffffffffff indicates that the device has not been configured, or
     * that the address of the device that last configured the scenes cluster is not known.
     * </p>
     * The attribute is of type {@link Long}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getLastConfiguredByAsync() {
        return read(ATTR_LASTCONFIGUREDBY);
    }


    /**
     * Synchronously get the <i>LastConfiguredBy</i> attribute
     * <p>
     * <br>
     * The LastConfiguredBy attribute is 64-bits in length and specifies the IEEE address
     * of the device that last configured the scene table.
     * <br>
     * The value 0xffffffffffffffff indicates that the device has not been configured, or
     * that the address of the device that last configured the scenes cluster is not known.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Long}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Long} attribute value, or null on error
     */
    public Long getLastConfiguredBy() {
        return (Long) readSync(ATTR_LASTCONFIGUREDBY);
    }


    /**
     * The Add Scene Command
     * <p>
     * The Add Scene command shall be addressed to a single device (not a group).
     * </p>
     *
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @param transitionTime {@link Integer} Transition time
     * @param sceneName {@link String} Scene Name
     * @param extensionFieldSets {@link List<ExtensionFieldSet>} Extension field sets
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> addSceneCommand(Integer groupId, Integer sceneId, Integer transitionTime, String sceneName, List<ExtensionFieldSet> extensionFieldSets) {
        AddSceneCommand command = new AddSceneCommand();

        // Set the fields
        command.setGroupId(groupId);
        command.setSceneId(sceneId);
        command.setTransitionTime(transitionTime);
        command.setSceneName(sceneName);
        command.setExtensionFieldSets(extensionFieldSets);

        return send(command);
    }


    /**
     * The View Scene Command
     * <p>
     * The View Scene command shall be addressed to a single device (not a group).
     * </p>
     *
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> viewSceneCommand(Integer groupId, Integer sceneId) {
        ViewSceneCommand command = new ViewSceneCommand();

        // Set the fields
        command.setGroupId(groupId);
        command.setSceneId(sceneId);

        return send(command);
    }


    /**
     * The Remove Scene Command
     * <p>
     * The Remove All Scenes may be addressed to a single device or to a group.
     * </p>
     *
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> removeSceneCommand(Integer groupId, Integer sceneId) {
        RemoveSceneCommand command = new RemoveSceneCommand();

        // Set the fields
        command.setGroupId(groupId);
        command.setSceneId(sceneId);

        return send(command);
    }


    /**
     * The Remove All Scenes Command
     * <p>
     * The Remove All Scenes may be addressed to a single device or to a group.
     * </p>
     *
     * @param groupId {@link Integer} Group ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> removeAllScenesCommand(Integer groupId) {
        RemoveAllScenesCommand command = new RemoveAllScenesCommand();

        // Set the fields
        command.setGroupId(groupId);

        return send(command);
    }


    /**
     * The Store Scene Command
     * <p>
     * The Store Scene command may be addressed to a single device or to a group.
     * </p>
     *
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> storeSceneCommand(Integer groupId, Integer sceneId) {
        StoreSceneCommand command = new StoreSceneCommand();

        // Set the fields
        command.setGroupId(groupId);
        command.setSceneId(sceneId);

        return send(command);
    }


    /**
     * The Recall Scene Command
     * <p>
     * The Recall Scene command may be addressed to a single device or to a group.
     * </p>
     *
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> recallSceneCommand(Integer groupId, Integer sceneId) {
        RecallSceneCommand command = new RecallSceneCommand();

        // Set the fields
        command.setGroupId(groupId);
        command.setSceneId(sceneId);

        return send(command);
    }


    /**
     * The Get Scene Membership Command
     * <p>
     * The Get Scene Membership command can be used to find an unused scene
     * number within the group when no commissioning tool is in the network, or for a
     * commissioning tool to get used scenes for a group on a single device or on all
     * devices in the group.
     * </p>
     *
     * @param groupId {@link Integer} Group ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getSceneMembershipCommand(Integer groupId) {
        GetSceneMembershipCommand command = new GetSceneMembershipCommand();

        // Set the fields
        command.setGroupId(groupId);

        return send(command);
    }


    /**
     * The  Add Scene Response
     *
     * @param status {@link Integer} Status
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> addSceneResponse(Integer status, Integer groupId, Integer sceneId) {
        AddSceneResponse command = new AddSceneResponse();

        // Set the fields
        command.setStatus(status);
        command.setGroupId(groupId);
        command.setSceneId(sceneId);

        return send(command);
    }


    /**
     * The  View Scene Response
     *
     * @param status {@link Integer} Status
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @param transitionTime {@link Integer} Transition time
     * @param sceneName {@link String} Scene Name
     * @param extensionFieldSets {@link List<ExtensionFieldSet>} Extension field sets
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> viewSceneResponse(Integer status, Integer groupId, Integer sceneId, Integer transitionTime, String sceneName, List<ExtensionFieldSet> extensionFieldSets) {
        ViewSceneResponse command = new ViewSceneResponse();

        // Set the fields
        command.setStatus(status);
        command.setGroupId(groupId);
        command.setSceneId(sceneId);
        command.setTransitionTime(transitionTime);
        command.setSceneName(sceneName);
        command.setExtensionFieldSets(extensionFieldSets);

        return send(command);
    }


    /**
     * The  Remove Scene Response
     *
     * @param status {@link Integer} Status
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> removeSceneResponse(Integer status, Integer groupId, Integer sceneId) {
        RemoveSceneResponse command = new RemoveSceneResponse();

        // Set the fields
        command.setStatus(status);
        command.setGroupId(groupId);
        command.setSceneId(sceneId);

        return send(command);
    }


    /**
     * The  Remove All Scenes Response
     *
     * @param status {@link Integer} Status
     * @param groupId {@link Integer} Group ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> removeAllScenesResponse(Integer status, Integer groupId) {
        RemoveAllScenesResponse command = new RemoveAllScenesResponse();

        // Set the fields
        command.setStatus(status);
        command.setGroupId(groupId);

        return send(command);
    }


    /**
     * The  Store Scene Response
     *
     * @param status {@link Integer} Status
     * @param groupId {@link Integer} Group ID
     * @param sceneId {@link Integer} Scene ID
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> storeSceneResponse(Integer status, Integer groupId, Integer sceneId) {
        StoreSceneResponse command = new StoreSceneResponse();

        // Set the fields
        command.setStatus(status);
        command.setGroupId(groupId);
        command.setSceneId(sceneId);

        return send(command);
    }


    /**
     * The  Get Scene Membership Response
     *
     * @param status {@link Integer} Status
     * @param capacity {@link Integer} Capacity
     * @param groupId {@link Integer} Group ID
     * @param sceneCount {@link Integer} Scene count
     * @param sceneList {@link List<Unsigned8BitInteger>} Scene list
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getSceneMembershipResponse(Integer status, Integer capacity, Integer groupId, Integer sceneCount, List<Unsigned8BitInteger> sceneList) {
        GetSceneMembershipResponse command = new GetSceneMembershipResponse();

        // Set the fields
        command.setStatus(status);
        command.setCapacity(capacity);
        command.setGroupId(groupId);
        command.setSceneCount(sceneCount);
        command.setSceneList(sceneList);

        return send(command);
    }


    /**
     * Add a binding for this cluster to the local node
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> bind() {
        return bind();
    }

}
