package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeDeviceAddress;
import org.bubblecloud.zigbee.v3.ZigBeeNetworkManager;
import org.bubblecloud.zigbee.v3.zcl.ZclAttribute;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclDataType;

/**
 * <b>Time</b> cluster implementation (<i>Cluster ID 0x000A</i>).
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclTimeCluster extends ZclCluster {
    // Cluster ID
    public static final int CLUSTER_ID = 0x000A;

    // Cluster Name
    public static final String CLUSTER_NAME = "Time";

    // Attribute constants
    public static final int ATTR_TIME = 0x0000;
    public static final int ATTR_TIMESTATUS = 0x0001;
    public static final int ATTR_TIMEZONE = 0x0002;
    public static final int ATTR_DSTSTART = 0x0003;
    public static final int ATTR_DSTEND = 0x0004;
    public static final int ATTR_DSTSHIFT = 0x0005;
    public static final int ATTR_STANDARDTIME = 0x0006;
    public static final int ATTR_LOCALTIME = 0x0007;

    // Attribute initialisation
    protected Map<Integer, ZclAttribute> initializeAttributes() {
        Map<Integer, ZclAttribute> attributeMap = new HashMap<Integer, ZclAttribute>(8);

        attributeMap.put(ATTR_TIME, new ZclAttribute(0, "Time", ZclDataType.UTCTIME, true, true, true, false));
        attributeMap.put(ATTR_TIMESTATUS, new ZclAttribute(1, "TimeStatus", ZclDataType.UNSIGNED_16_BIT_INTEGER, false, true, true, false));
        attributeMap.put(ATTR_TIMEZONE, new ZclAttribute(2, "TimeZone", ZclDataType.SIGNED_32_BIT_INTEGER, false, true, true, false));
        attributeMap.put(ATTR_DSTSTART, new ZclAttribute(3, "DstStart", ZclDataType.UNSIGNED_32_BIT_INTEGER, false, true, true, false));
        attributeMap.put(ATTR_DSTEND, new ZclAttribute(4, "DstEnd", ZclDataType.UNSIGNED_32_BIT_INTEGER, false, true, true, false));
        attributeMap.put(ATTR_DSTSHIFT, new ZclAttribute(5, "DstShift", ZclDataType.SIGNED_32_BIT_INTEGER, false, true, true, false));
        attributeMap.put(ATTR_STANDARDTIME, new ZclAttribute(6, "StandardTime", ZclDataType.SIGNED_32_BIT_INTEGER, false, true, false, false));
        attributeMap.put(ATTR_LOCALTIME, new ZclAttribute(7, "LocalTime", ZclDataType.SIGNED_32_BIT_INTEGER, false, true, false, false));

        return attributeMap;
    }

    /**
     * Default constructor.
     */
    public ZclTimeCluster(final ZigBeeNetworkManager zigbeeManager, final ZigBeeDeviceAddress zigbeeAddress) {
        super(zigbeeManager, zigbeeAddress, CLUSTER_ID, CLUSTER_NAME);
    }



    /**
     * Set the <i>Time</i> attribute
     * <p>
     * The Time attribute is 32-bits in length and holds the time value of a real time
     * clock. This attribute has data type UTCTime, but note that it may not actually be
     * synchronised to UTC - see discussion of the TimeStatus attribute below.
     * <br>
     * If the Master bit of the TimeStatus attribute has a value of 0, writing to this
     * attribute shall set the real time clock to the written value, otherwise it cannot be
     * written. The value 0xffffffff indicates an invalid time.
     * </p>
     * The attribute is of type {@link Calendar}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param time the {@link Calendar} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setTime(final Object value) {
        return write(ATTR_TIME, ZclDataType.UTCTIME, value);
    }


    /**
     * Get the <i>Time</i> attribute
     * <p>
     * The Time attribute is 32-bits in length and holds the time value of a real time
     * clock. This attribute has data type UTCTime, but note that it may not actually be
     * synchronised to UTC - see discussion of the TimeStatus attribute below.
     * <br>
     * If the Master bit of the TimeStatus attribute has a value of 0, writing to this
     * attribute shall set the real time clock to the written value, otherwise it cannot be
     * written. The value 0xffffffff indicates an invalid time.
     * </p>
     * The attribute is of type {@link Calendar}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTimeAsync() {
        return read(ATTR_TIME);
    }


    /**
     * Synchronously get the <i>Time</i> attribute
     * <p>
     * The Time attribute is 32-bits in length and holds the time value of a real time
     * clock. This attribute has data type UTCTime, but note that it may not actually be
     * synchronised to UTC - see discussion of the TimeStatus attribute below.
     * <br>
     * If the Master bit of the TimeStatus attribute has a value of 0, writing to this
     * attribute shall set the real time clock to the written value, otherwise it cannot be
     * written. The value 0xffffffff indicates an invalid time.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Calendar}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Calendar} attribute value, or null on error
     */
    public Calendar getTime() {
        return (Calendar) readSync(ATTR_TIME);
    }


    /**
     * Set the <i>TimeStatus</i> attribute
     * <p>
     * <br>
     * The TimeStatus attribute holds a number of bit fields.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param timeStatus the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setTimeStatus(final Object value) {
        return write(ATTR_TIMESTATUS, ZclDataType.UNSIGNED_16_BIT_INTEGER, value);
    }


    /**
     * Get the <i>TimeStatus</i> attribute
     * <p>
     * <br>
     * The TimeStatus attribute holds a number of bit fields.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTimeStatusAsync() {
        return read(ATTR_TIMESTATUS);
    }


    /**
     * Synchronously get the <i>TimeStatus</i> attribute
     * <p>
     * <br>
     * The TimeStatus attribute holds a number of bit fields.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getTimeStatus() {
        return (Integer) readSync(ATTR_TIMESTATUS);
    }


    /**
     * Set the <i>TimeZone</i> attribute
     * <p>
     * <br>
     * The TimeZone attribute indicates the local time zone, as a signed offset in seconds
     * from the Time attribute value. The value 0xffffffff indicates an invalid time zone.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param timeZone the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setTimeZone(final Object value) {
        return write(ATTR_TIMEZONE, ZclDataType.SIGNED_32_BIT_INTEGER, value);
    }


    /**
     * Get the <i>TimeZone</i> attribute
     * <p>
     * <br>
     * The TimeZone attribute indicates the local time zone, as a signed offset in seconds
     * from the Time attribute value. The value 0xffffffff indicates an invalid time zone.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTimeZoneAsync() {
        return read(ATTR_TIMEZONE);
    }


    /**
     * Synchronously get the <i>TimeZone</i> attribute
     * <p>
     * <br>
     * The TimeZone attribute indicates the local time zone, as a signed offset in seconds
     * from the Time attribute value. The value 0xffffffff indicates an invalid time zone.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getTimeZone() {
        return (Integer) readSync(ATTR_TIMEZONE);
    }


    /**
     * Set the <i>DstStart</i> attribute
     * <p>
     * <br>
     * The DstStart attribute indicates the DST start time in seconds. The value 0xffffffff
     * indicates an invalid DST start time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param dstStart the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDstStart(final Object value) {
        return write(ATTR_DSTSTART, ZclDataType.UNSIGNED_32_BIT_INTEGER, value);
    }


    /**
     * Get the <i>DstStart</i> attribute
     * <p>
     * <br>
     * The DstStart attribute indicates the DST start time in seconds. The value 0xffffffff
     * indicates an invalid DST start time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDstStartAsync() {
        return read(ATTR_DSTSTART);
    }


    /**
     * Synchronously get the <i>DstStart</i> attribute
     * <p>
     * <br>
     * The DstStart attribute indicates the DST start time in seconds. The value 0xffffffff
     * indicates an invalid DST start time.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getDstStart() {
        return (Integer) readSync(ATTR_DSTSTART);
    }


    /**
     * Set the <i>DstEnd</i> attribute
     * <p>
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that the three attributes DstStart, DstEnd and DstShift are optional, but if any
     * one of them is implemented the other two must also be implemented.
     * Note that this attribute should be set to a new value once every year.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute.
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param dstEnd the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDstEnd(final Object value) {
        return write(ATTR_DSTEND, ZclDataType.UNSIGNED_32_BIT_INTEGER, value);
    }


    /**
     * Get the <i>DstEnd</i> attribute
     * <p>
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that the three attributes DstStart, DstEnd and DstShift are optional, but if any
     * one of them is implemented the other two must also be implemented.
     * Note that this attribute should be set to a new value once every year.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute.
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDstEndAsync() {
        return read(ATTR_DSTEND);
    }


    /**
     * Synchronously get the <i>DstEnd</i> attribute
     * <p>
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that the three attributes DstStart, DstEnd and DstShift are optional, but if any
     * one of them is implemented the other two must also be implemented.
     * Note that this attribute should be set to a new value once every year.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute.
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getDstEnd() {
        return (Integer) readSync(ATTR_DSTEND);
    }


    /**
     * Set the <i>DstShift</i> attribute
     * <p>
     * <br>
     * The DstShift attribute represents a signed offset in seconds from the standard time,
     * to be applied between the times DstStart and DstEnd to calculate the Local Time.
     * The value 0xffffffff indicates an invalid DST shift.
     * <br>
     * The range of this attribute is +/- one day. Note that the actual range of DST values
     * employed by countries is much smaller than this, so the manufacturer has the
     * option to impose a smaller range.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param dstShift the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDstShift(final Object value) {
        return write(ATTR_DSTSHIFT, ZclDataType.SIGNED_32_BIT_INTEGER, value);
    }


    /**
     * Get the <i>DstShift</i> attribute
     * <p>
     * <br>
     * The DstShift attribute represents a signed offset in seconds from the standard time,
     * to be applied between the times DstStart and DstEnd to calculate the Local Time.
     * The value 0xffffffff indicates an invalid DST shift.
     * <br>
     * The range of this attribute is +/- one day. Note that the actual range of DST values
     * employed by countries is much smaller than this, so the manufacturer has the
     * option to impose a smaller range.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDstShiftAsync() {
        return read(ATTR_DSTSHIFT);
    }


    /**
     * Synchronously get the <i>DstShift</i> attribute
     * <p>
     * <br>
     * The DstShift attribute represents a signed offset in seconds from the standard time,
     * to be applied between the times DstStart and DstEnd to calculate the Local Time.
     * The value 0xffffffff indicates an invalid DST shift.
     * <br>
     * The range of this attribute is +/- one day. Note that the actual range of DST values
     * employed by countries is much smaller than this, so the manufacturer has the
     * option to impose a smaller range.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getDstShift() {
        return (Integer) readSync(ATTR_DSTSHIFT);
    }


    /**
     * Get the <i>StandardTime</i> attribute
     * <p>
     * <br>
     * A device may derive the time by reading the Time and TimeZone attributes
     * and adding them together. If implemented however, the optional StandardTime
     * attribute indicates this time directly. The value 0xffffffff indicates an invalid
     * Standard Time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getStandardTimeAsync() {
        return read(ATTR_STANDARDTIME);
    }


    /**
     * Synchronously get the <i>StandardTime</i> attribute
     * <p>
     * <br>
     * A device may derive the time by reading the Time and TimeZone attributes
     * and adding them together. If implemented however, the optional StandardTime
     * attribute indicates this time directly. The value 0xffffffff indicates an invalid
     * Standard Time.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getStandardTime() {
        return (Integer) readSync(ATTR_STANDARDTIME);
    }


    /**
     * Get the <i>LocalTime</i> attribute
     * <p>
     * <br>
     * A device may derive the time by reading the Time, TimeZone, DstStart, DstEnd
     * and DstShift attributes and performing the calculation. If implemented however,
     * the optional LocalTime attribute indicates this time directly. The value 0xffffffff
     * indicates an invalid Local Time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getLocalTimeAsync() {
        return read(ATTR_LOCALTIME);
    }


    /**
     * Synchronously get the <i>LocalTime</i> attribute
     * <p>
     * <br>
     * A device may derive the time by reading the Time, TimeZone, DstStart, DstEnd
     * and DstShift attributes and performing the calculation. If implemented however,
     * the optional LocalTime attribute indicates this time directly. The value 0xffffffff
     * indicates an invalid Local Time.
     * </p>
     * This method will block until the response is received or a timeout occurs.<br>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Integer} attribute value, or null on error
     */
    public Integer getLocalTime() {
        return (Integer) readSync(ATTR_LOCALTIME);
    }


    /**
     * Add a binding for this cluster to the local node
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> bind() {
        return bind();
    }

}
